export const REQUEST_SINGLE_INFO = "REQUEST_SINGLE_INFO";
export type REQUEST_SINGLE_INFO = typeof REQUEST_SINGLE_INFO;

export const RECIEVE_SINGLE_INFO = "RECIEVE_SINGLE_INFO";
export type RECIEVE_SINGLE_INFO = typeof RECIEVE_SINGLE_INFO;

export const FETCH_SINGLE_INFO_FAILED = "FETCH_SINGLE_INFO_FAILED";
export type FETCH_SINGLE_INFO_FAILED = typeof FETCH_SINGLE_INFO_FAILED;

export const FETCH_SINGLE_INFO = "FETCH_SINGLE_INFO";
export type FETCH_SINGLE_INFO = typeof FETCH_SINGLE_INFO;

export const DOWNLOAD_SINGLE = "DOWNLAOD_SINGLE";
export type DOWNLOAD_SINGLE = typeof DOWNLOAD_SINGLE; 

export const DOWNLOAD_SINGLE_FAILED = "DOWNLOAD_SINGLE_FAILED";
export type DOWNLOAD_SINGLE_FAILED = typeof DOWNLOAD_SINGLE_FAILED;