export const FETCH_PLAYLIST_INFO = "FETCH_PLAYLIST_INFO";
export type FETCH_PLAYLIST_INFO = typeof FETCH_PLAYLIST_INFO;

export const FETCH_PLAYLIST_INFO_SUCCESS = "FETCH_PLAYLIST_INFO_SUCCESS";
export type FETCH_PLAYLIST_INFO_SUCCESS = typeof FETCH_PLAYLIST_INFO_SUCCESS;